### ISSUE TITLE
NuGet package capitalisation issue?

### ISSUE THREAD

**Issue by niwrA** [StefH/SimMetrics.Net#2]
When I'm trying to restore packages for a project that references this package, I am getting an error. It seems that there's a strange issue. It is trying to access: 

https://api.nuget.org/v3-flatcontainer/simmetrics.net/index.json <-- does not work

Which gives a 504. but if I change the caps (suggested by a colleague to try), I do get a list of package versions ... what's going on here? Is that something under your control?

https://api.nuget.org/v3-flatcontainer/SimMetrics.Net/index.json <-- works

**Comment by StefH** [comment]
Which framework do you use for you main application?

**Comment by StefH** [comment]
When I just install this in a .net 4.5.2 project, it works ok:

```
Attempting to gather dependency information for package 'SimMetrics.Net.1.0.4' with respect to project 'ConsoleApplication1SIM', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'SimMetrics.Net.1.0.4' with DependencyBehavior 'Lowest'
Resolving actions to install package 'SimMetrics.Net.1.0.4'
Resolved actions to install package 'SimMetrics.Net.1.0.4'
  GET https://api.nuget.org/v3-flatcontainer/simmetrics.net/1.0.4/simmetrics.net.1.0.4.nupkg
  OK https://api.nuget.org/v3-flatcontainer/simmetrics.net/1.0.4/simmetrics.net.1.0.4.nupkg 648ms
Installing SimMetrics.Net 1.0.4.
Adding package 'SimMetrics.Net.1.0.4' to folder 'C:\dev\_\ConsoleApplication1SIM\packages'
Added package 'SimMetrics.Net.1.0.4' to folder 'C:\dev\_\ConsoleApplication1SIM\packages'
Added package 'SimMetrics.Net.1.0.4' to 'packages.config'
Successfully installed 'SimMetrics.Net 1.0.4' to ConsoleApplication1SIM
```

**Comment by niwrA** [comment]
I was trying to install SimMetrics.Net, which references this package, and it fails, both the source and the package (as referenced above)

**Comment by niwrA** [comment]
Interestingly, the problem seems to have been temporary - I just checked https://api.nuget.org/v3-flatcontainer/simmetrics.net/index.json and this now works again

**Comment by StefH** [comment]
Maybe issue with NuGet.org
